/* Từ điển 简体中文 (zh): khóa = câu tiếng Việt gốc. __ready=true khi đã dịch đủ toàn trang. */
window.I18N=window.I18N||{};
window.I18N.zh={
  "Giới thiệu":"学校简介",
  "Chuyên ngành":"专业设置",
  "Trường chính":"深圳大学本部",
  "Học phí":"学费",
  "Thi đầu vào":"入学考试",
  "Xét tuyển 2027":"2027招生",
  "Học bổng":"奖学金",
  "Chuyên ngành duy nhất, định hướng thật rõ":"专业只有一个，方向非常明确",
  "Tập trung vào tiếng Trung thương mại, kết hợp kiến thức kinh doanh và công nghệ để sẵn sàng làm việc tại doanh nghiệp Nhật – Trung.":"以商务中文为核心，结合商科与信息技术知识，为进入中日企业工作做好准备。",
  "1 chuyên ngành chính + 2 chuyên ngành phụ":"1个主修专业＋2个辅修专业",
  "Học tiếng Trung thương mại làm trục chính, mở rộng thêm kinh doanh hoặc công nghệ thông tin. Bấm vào thẻ để xem giáo trình chi tiết trên website trường.":"以商务中文为主线，可再拓展到经营管理或信息技术。点击卡片可前往学校官网查看课程详情。",
  "Xem giáo trình ›":"查看课程 ›",
  "Đại học Thâm Quyến: trường công lập ngay giữa thành phố đổi mới sáng tạo":"深圳大学本部——创新之城深圳的公立综合性大学",
  "SZU Tokyo đào tạo theo chương trình của Đại học Thâm Quyến (深圳大学) ở Trung Quốc. Bằng cấp là bằng chính quy do cơ sở chính cấp.":"东京校区按中国深圳大学的培养方案授课，毕业获得由本部颁发的正规学位。",
  "Năm thành lập":"创办年份",
  "Cơ sở: Việt Hải & Lệ Hồ":"校区（粤海、丽湖）",
  "Tổng diện tích":"占地面积",
  "Sinh viên":"在校生（约）",
  "Vị trí: quận Nam Sơn (南山区), Thâm Quyến, Quảng Đông, Trung Quốc":"位置：中国广东省深圳市南山区",
  "Xếp hạng thế giới":"世界大学排名",
  "Cập nhật: 06/10/2026":"更新：2026年10月6日",
  "Hạng 27 trong các đại học nội địa Trung Quốc, tăng 36 bậc":"中国内地高校第27名，较去年上升36位",
  "Công bố ngày 30/9/2026":"2026年9月30日发布",
  "Bảng xếp hạng Thượng Hải (ShanghaiRanking)":"软科世界大学学术排名（上海）",
  "🔬 Hóa lý: hạng 9 thế giới (US News)":"🔬 物理化学：世界第9（US News）",
  "⚛️ Khoa học nano: hạng 10 thế giới (US News)":"⚛️ 纳米科学：世界第10（US News）",
  "Xem bảng xếp hạng mới nhất tại trang chính thức:":"最新排名请查看官方网站：",
  "Từ nền tảng đến thực hành doanh nghiệp":"从基础到企业实践",
  "Thời gian học, tín chỉ và văn bằng":"学制、学分与学位",
  "Minh bạch từng khoản phí":"每一项费用都清清楚楚",
  "Hai hình thức thi, tùy trình độ tiếng Trung":"按中文水平分两种考试",
  "Điều kiện, hình thức xét tuyển & cách nộp hồ sơ":"报名条件、选拔方式与申请方法",
  "5 loại học bổng đồng hành cùng bạn":"5类奖学金助你前行",
  "Tài liệu & đăng ký":"资料与报名",
  "Lộ trình học 4 năm":"4年学习路线",
  "Học chế & bằng cấp":"学制与学位",
  "Học phí chi tiết":"学费详情",
  "Tuyển sinh khóa 2027":"2027届招生",
  "Học bổng chi tiết":"奖学金详情",
  "Liên kết hữu ích":"实用链接",
  "Tuyển sinh 2 kỳ: Tháng 4 & Tháng 10":"每年招生2次：4月与10月",
  "Đại học Thâm Quyến":"深圳大学",
  "Học tiếng Trung thương mại ngay giữa Tokyo và nhận bằng đại học chính quy 100% do cơ sở chính tại Trung Quốc cấp.":"在东京学习商务中文，并获得由中国本部颁发的正规大学学位。",
  "Xem học bổng 🎁":"查看奖学金 🎁",
  "Tính học phí 💴":"计算学费 💴",
  "Thông tin nhanh":"快速了解",
  "Bằng chính quy 100%":"100%正规学位",
  "Do Đại học Thâm Quyến (Trung Quốc) cấp":"由中国深圳大学颁发",
  "Yêu cầu tiếng Nhật ≈ N3+":"日语要求约N3以上",
  "Có chứng chỉ thì càng tốt":"持有证书更佳",
  "Nhận mọi loại visa":"接收各类签证",
  "Trừ visa thực tập sinh":"技能实习生除外",
  "Ga Yotsuya · 2–3 phút đi bộ":"四谷站步行2–3分钟",
  "四ツ谷駅 – di chuyển cực tiện":"通学十分便利",
  "Cuộn xuống":"向下滑动",
  "năm":"年",
  "Chương trình đại học":"本科课程",
  "Bằng chính quy":"正规学位",
  "kỳ/năm":"次/年",
  "Tuyển sinh tháng 4 & 10":"4月与10月招生",
  "tuyến":"条线路",
  "Tàu qua ga Yotsuya (JR, Marunouchi, Namboku)":"四谷站（JR、丸之内线、南北线）",
  "Chuyên ngành chính":"主修专业",
  "Chuyên ngành phụ":"辅修专业",
  "Tiếng Trung thương mại":"商务中文",
  "ビジネス中国語":"ビジネス中国語",
  "Quản trị kinh doanh":"经营管理",
  "経営学":"経営学",
  "Truyền thông & Công nghệ thông tin":"信息传播学",
  "情報コミュニケーション学":"情報コミュニケーション学",
  "Tất cả đường dẫn chính thức để bạn tìm hiểu và nộp hồ sơ.":"了解信息与提交申请所需的全部官方链接。",
  "Ga gần trường: 四ツ谷駅 (Yotsuya)":"最近车站：四谷站",
  "Đi bộ khoảng 2–3 phút · các tuyến JR Chuo, Marunouchi, Namboku":"步行约2–3分钟 · JR中央线、丸之内线、南北线",
  "🗺️ Mở Google Map":"🗺️ 打开谷歌地图",
  "Trang học phí chính thức":"官方学费页面",
  "Hồ sơ & đề thi mẫu":"申请材料与样题",
  "Dành cho sinh viên quốc tế":"面向国际学生",
  "Tài liệu tiếng Việt":"越南语资料",
  "Ngày thi, lịch và hướng dẫn nộp hồ sơ":"考试日期、日程与申请指南",
  "Xin tài liệu gửi về nhà":"邮寄资料",
  "Đăng ký nhận tài liệu qua đường bưu điện":"申请通过邮寄方式获取资料",
  "Đăng ký Open Campus":"报名参加开放日",
  "Đến trường tham quan và trao đổi trực tiếp":"到校参观并当面交流",
  "· Đại học Thâm Quyến Tokyo Campus":"· 深圳大学东京校区",
  "四ツ谷駅 (Yotsuya) – 2–3 phút đi bộ":"四谷站步行2–3分钟",
  "Tuyển sinh tháng 4 & tháng 10":"4月与10月招生",
  "Thông tin trong trang chỉ mang tính tham khảo và có thể thay đổi. Vui lòng xác nhận lại học phí, học bổng và lịch thi trên website chính thức":"本页信息仅供参考，可能会有变动。提交申请前，请在官方网站确认学费、奖学金和考试日程：",
  "trước khi nộp hồ sơ.":"",
  "Khoa":"院系",
  "📈 Kinh doanh":"📈 商科",
  "2,72 km²":"2.72平方公里",
  "≈ 503 man":"≈ 503万日元",
  "· FAX 03-6384-2208":"· 传真 03-6384-2208",
  "__title":"深圳大学东京校区 – 招生指南",
  "__note":"※ 详细正文正在陆续翻译，部分内容暂时仍为越南语。",
  "Đại học Thâm Quyến Tokyo Campus – Cẩm nang tuyển sinh":"深圳大学东京校区 – 招生指南",
  "Đại học Thâm Quyến · Tokyo Campus":"深圳大学 · 东京校区",
  "Tiếng Trung hướng thương mại":"面向商务的中文",
  "Bằng đại học là bằng chính quy 100% do cơ sở chính ở Trung Quốc cấp. Ngoài tiếng Trung thương mại, sinh viên còn được học thêm nhiều mảng kiến thức thực tế.":"本科学位为由中国本部颁发的100%正规学位。除商务中文外，学生还可学习多方面的实用知识。",
  "🌐 Thương mại quốc tế":"🌐 国际贸易",
  "💻 IT – Công nghệ":"💻 IT – 信息技术",
  "🤝 Kỹ năng doanh nghiệp thực tế":"🤝 实用的企业职场技能",
  "Điều kiện & lưu ý đầu vào":"入学条件与注意事项",
  "Yêu cầu tiếng Nhật khoảng":"日语要求约",
  "N3 trở lên":"N3 以上",
  "(có chứng chỉ thì tốt).":"（有证书更佳）。",
  "Biết tiếng Trung được ưu tiên, có thể thi theo hình thức khác.":"懂中文者优先，也可选择其他考试方式。",
  "Tỷ lệ chuyên cần (":"出勤率（",
  ") càng cao càng tốt.":"）越高越好。",
  "Trường nhận các loại visa,":"学校接收各类签证，",
  "trừ thực tập sinh":"技能实习生除外",
  "Tuyển sinh":"招生时间：",
  "tháng 4":"4月",
  "và":"和",
  "tháng 10":"10月",
  "(tháng 10 yêu cầu biết tiếng Trung).":"（10月入学需具备中文基础）。",
  "🏛️ Thông tin chính thức của trường":"🏛️ 学校官方信息",
  "Tên trường":"学校名称",
  "Tên thường gọi: 深圳大学東京校":"通称：深圳大学東京校",
  "Khoa Tiếng Trung (中国語学部)":"中文学部（中国語学部）",
  "Ngành":"专业",
  "Tiếng Trung thương mại (ビジネス中国語学科)":"商务中文（ビジネス中国語学科）",
  "Ngành phụ":"辅修专业",
  "Quản trị kinh doanh (Đổi mới & Khởi nghiệp)":"经营管理（创新与创业）",
  "Truyền thông thông tin (Công nghệ ứng dụng Mobile Internet)":"信息传播（移动互联网应用技术）",
  "Địa chỉ":"地址",
  "〒160-0004 Tokyo, Shinjuku-ku, Yotsuya 1-22-5, tầng 3":"〒160-0004 东京都新宿区四谷1-22-5，3层",
  "Cách ga Yotsuya khoảng 3 phút đi bộ (JR Chuo, Marunouchi, Namboku)":"距四谷站步行约3分钟（JR中央线、丸之内线、南北线）",
  "Liên hệ":"联系方式",
  "Chọn từng năm để xem các môn học chính. Ngoài môn bắt buộc còn có nhiều môn tự chọn khác.":"请选择年级查看主要课程。除必修课外，还有许多选修课。",
  "Năm 1 · Nền tảng":"第1年 · 基础",
  "Năm 2 · Nâng cao":"第2年 · 进阶",
  "Năm 3 · Thương mại":"第3年 · 商务",
  "Năm 4 · Thực hành":"第4年 · 实践",
  "Nền tảng":"基础",
  "Xây chắc 4 kỹ năng tiếng Trung và hiểu bối cảnh văn hóa – kinh tế.":"打牢中文四项技能，了解文化与经济背景。",
  "Tiếng Trung cơ bản 4 kỹ năng":"中文基础四项技能",
  "Văn hóa Nhật – Trung":"日中文化",
  "Kinh tế Greater Bay Area":"粤港澳大湾区经济",
  "Tiếng Anh":"英语",
  "Tự chọn: Tiếng Anh thương mại, Thiết kế sự nghiệp và các môn khác":"选修：商务英语、职业规划设计及其他课程",
  "Nâng cao":"进阶",
  "Nâng trình tiếng Trung lên trung cấp, đào sâu Hán tự và ngữ pháp.":"将中文提升至中级水平，深入学习汉字与语法。",
  "Tiếng Trung trung cấp":"中级中文",
  "Văn hóa trà Trung Quốc":"中国茶文化",
  "Hán tự & giải thích chữ Hán":"汉字与汉字讲解",
  "Ngữ pháp nâng cao":"高级语法",
  "Giới thiệu Thâm Quyến":"深圳概况",
  "Tự chọn: Tiếng Anh thương mại, tiếng Quảng Đông, từ vựng & ngữ pháp khó và các môn khác":"选修：商务英语、粤语、疑难词汇与语法及其他课程",
  "Thương mại":"商务",
  "Chuyên sâu tiếng Trung thương mại, đàm phán và pháp luật.":"深入学习商务中文、谈判与法律。",
  "Nghe nói thương mại":"商务听说",
  "Đọc hiểu tài liệu kinh doanh":"商务文献阅读",
  "Đàm phán thương mại quốc tế":"国际商务谈判",
  "Báo chí kinh tế":"经济新闻",
  "Luật pháp Trung Quốc":"中国法律",
  "Hướng dẫn luận văn":"论文指导",
  "Tổng quan về Trung Quốc":"中国概况",
  "Đọc hiểu kinh tế Trung Quốc":"中国经济阅读",
  "Thực hành":"实践",
  "Hoàn thiện luận văn và thực tập tại doanh nghiệp.":"完成毕业论文并进行企业实习。",
  "Hội thoại thương mại nâng cao":"高级商务会话",
  "Nghiệp vụ thương mại quốc tế":"国际贸易实务",
  "Làm luận văn":"撰写论文",
  "Thực tập doanh nghiệp":"企业实习",
  "Tư vấn luận văn":"论文咨询",
  "4 năm":"4年",
  "Thời gian học tiêu chuẩn.":"标准修业年限。",
  "Tối đa 8 năm":"最长8年",
  "Thời gian được phép theo học.":"允许在校学习的最长年限。",
  "Tối thiểu 2 năm":"最短2年",
  "Có thể tốt nghiệp sớm nếu đáp ứng điều kiện chuyển tiếp / nhảy cấp của trường.":"满足学校转入/跳级条件的，可提前毕业。",
  "Cử nhân Văn học":"文学学士",
  "📚 Tín chỉ cần để tốt nghiệp":"📚 毕业所需学分",
  "Tổng cộng":"合计",
  "tín chỉ":"学分",
  "Môn cơ bản bắt buộc":"基础必修课",
  "Chuyên ngành bắt buộc":"专业必修课",
  "Chuyên ngành tự chọn":"专业选修课",
  "Giáo dục đại cương":"通识教育",
  "Thực tiễn xã hội":"社会实践",
  "Luận văn tốt nghiệp":"毕业论文",
  "Tổng":"总计",
  "Tín chỉ của ngành phụ (Quản trị kinh doanh, Truyền thông thông tin) nằm trong nhóm môn liên quan chuyên ngành.":"辅修专业（经营管理、信息传播）的学分计入专业相关课程组。",
  "🏅 Văn bằng nhận được":"🏅 可获得的学位证书",
  "Sinh viên đủ tín chỉ quy định được Đại học Thâm Quyến cơ sở chính cấp":"修满规定学分的学生，将由深圳大学本部颁发",
  "bằng tốt nghiệp và bằng học vị":"毕业证书和学位证书",
  "được Bộ Giáo dục Trung Quốc công nhận. Người hoàn thành ngành phụ còn nhận thêm":"，并获中国教育部认可。完成辅修专业者另可获得",
  "giấy chứng nhận hoàn thành":"结业证明",
  "riêng.":"。",
  "⏩ Chuyển tiếp / nhảy cấp":"⏩ 转入 / 跳级",
  "Nếu đáp ứng điều kiện của trường, bạn có thể tốt nghiệp sớm nhất sau 2 năm. Hãy trao đổi trực tiếp tại Open Campus hoặc buổi phỏng vấn tư vấn riêng.":"符合学校条件的话，最快2年即可毕业。请在开放日或个别咨询面谈时直接询问。",
  "📕 Đăng ký Open Campus":"📕 报名参加开放日",
  "Đơn vị: yên Nhật (¥). Học phí có thể chia thành 2 lần đóng mỗi năm, tương ứng 2 học kỳ.":"单位：日元（¥）。学费可分为每年2次缴纳，对应2个学期。",
  "Khoản phí":"费用项目",
  "Năm 1":"第1年",
  "Năm 2–4 (mỗi năm)":"第2–4年（每年）",
  "Phí nhập học":"入学费",
  "Phí cơ sở vật chất":"设施费",
  "Phí giáo dục bổ sung":"附加教育费",
  "Phí hoạt động + hội học sinh":"活动费 + 学生会费",
  "Giáo trình":"教材费",
  "Tổng khoảng 4 năm":"4年合计约",
  "Năm 2":"第2年",
  "Năm 3":"第3年",
  "Năm 4":"第4年",
  "Chia 2 lần đóng":"分2次缴纳",
  "1 năm có 2 học kỳ nên học phí được chia đôi, đóng thành 2 lần.":"一年有2个学期，学费分成两半，分2次缴纳。",
  "Nhảy cấp tiết kiệm":"跳级省钱",
  "Có HSK5+ có thể thi nhảy cấp lên năm 2 hoặc năm 3 để tiết kiệm thời gian và học phí.":"持有HSK5级以上可参加考试跳级至第2或第3年，节省时间和学费。",
  "Phí xét tín chỉ":"学分认定费",
  "Người nhảy cấp / chuyển trường / nhập học tháng 10:":"跳级 / 转校 / 10月入学者：",
  "20,000¥ / 1 môn":"每门 20,000¥",
  "Lệ phí thi đầu vào: 35,000¥.":"入学考试费：35,000¥。",
  "Có giấy tiến cử + JLPT N3 có thể được giảm một nửa.":"持有推荐信 + JLPT N3 者可减半。",
  "🧮 Ước tính chi phí năm 1":"🧮 第1年费用估算",
  "Chọn chứng chỉ ngoại ngữ để xem mức học bổng ngoại ngữ tương ứng (xét lúc nhập học). Chỉ mang tính tham khảo.":"选择外语证书，查看对应的外语奖学金金额（入学时审核）。仅供参考。",
  "Chứng chỉ ngoại ngữ (còn hiệu lực)":"外语证书（在有效期内）",
  "Chưa có chứng chỉ":"暂无证书",
  "Tính thêm học bổng tân sinh viên 150,000¥ (nếu được xét)":"另计新生奖学金150,000¥（如获审核通过）",
  "Tổng chi phí năm 1":"第1年总费用",
  "Học bổng ngoại ngữ":"外语奖学金",
  "Học bổng tân sinh viên":"新生奖学金",
  "Ước tính còn lại":"预计剩余费用",
  "Học bổng do trường xét duyệt, không phải khoản được đảm bảo.":"奖学金由学校审核决定，并非保证发放的款项。",
  "Chưa biết tiếng Trung":"尚未学过中文",
  "Thi dành cho người mới":"面向初学者的考试",
  "Phỏng vấn":"面试",
  "10 phút":"10分钟",
  "Viết luận":"作文",
  "60 phút · có thể thi bằng tiếng Việt":"60分钟 · 可用越南语应试",
  "Từ HSK4":"HSK4级以上",
  "Thi dành cho người có tiếng Trung":"面向有中文基础者的考试",
  "Thi viết tiếng Trung":"中文笔试",
  "60 phút":"60分钟",
  "Biết tiếng Trung có thể thi nhảy cấp để":"懂中文者可参加跳级考试，",
  "học thẳng năm 2 hoặc năm 3":"直接就读第2年或第3年",
  "đại học.":"本科课程。",
  "Du học ngắn hạn":"短期留学",
  "Trao đổi tại cơ sở chính ở Trung Quốc":"前往中国本部交流",
  "Từ năm 2, sinh viên có thể đăng ký đi trao đổi tại Đại học Thâm Quyến cơ sở chính, trong 1 học kỳ hoặc 1 năm. Trong thời gian đó học phí vẫn đóng bên Nhật như bình thường.":"从第2年起，学生可申请到深圳大学本部交流1个学期或1年。交流期间学费仍照常在日本缴纳。",
  "Thâm Quyến":"深圳",
  "1 kỳ hoặc 1 năm":"1学期或1年",
  "Tóm tắt từ hướng dẫn tuyển sinh chính thức năm 2027. Học sinh nước ngoài nên đọc kỹ tab \"Lưu học sinh\" và tài liệu tiếng Việt của trường.":"摘自2027年官方招生简章。外国学生请务必仔细阅读“留学生”标签页和学校的越南语资料。",
  "🎯 Trường mong muốn tìm kiếm những bạn…":"🎯 学校希望招收这样的你……",
  "Muốn thành thạo tiếng Trung thương mại để hoạt động toàn cầu trong các lĩnh vực như thương mại, du lịch, sản xuất, khởi nghiệp, IT.":"希望熟练掌握商务中文，在贸易、旅游、制造、创业、IT等领域活跃于全球。",
  "Quan tâm đến Thâm Quyến và Đại học Thâm Quyến, nơi tiêu biểu cho tinh thần khởi nghiệp, thực hành và hướng ra toàn cầu.":"关注深圳及深圳大学——创业精神、实践导向和全球视野的代表。",
  "Có hiểu biết cơ bản về văn hóa, kinh tế Trung Quốc và mong muốn tìm hiểu học thuật sâu hơn.":"对中国文化和经济有基本了解，并渴望深入学术探究。",
  "Điều kiện":"报名条件",
  "Lưu học sinh":"留学生",
  "Hình thức xét tuyển":"选拔方式",
  "Nộp hồ sơ":"提交材料",
  "Điều kiện chung":"共同条件",
  "Dành cho người có quốc tịch Nhật, hoặc quốc tịch nước ngoài khác Trung Quốc (kể cả Hồng Kông, Macao, Đài Loan). Cần thuộc một trong các trường hợp:":"面向日本国籍，或中国以外外国国籍（含香港、澳门、台湾）者。需符合下列情形之一：",
  "Đã tốt nghiệp THPT, hoặc dự kiến tốt nghiệp tháng 3/2027.":"已高中毕业，或预计2027年3月毕业。",
  "Hoàn thành 12 năm giáo dục phổ thông, hoặc dự kiến hoàn thành tháng 3/2027.":"已完成12年中小学教育，或预计2027年3月完成。",
  "Đã/sắp hoàn thành khóa cao đẳng nghề (senmon) có quyền vào đại học.":"已/即将完成具有大学入学资格的专修学校（专门学校）课程。",
  "Đỗ kỳ thi tương đương tốt nghiệp THPT của Bộ Giáo dục Nhật.":"通过日本文部科学省的高中毕业程度认定考试。",
  "Hoàn thành/dự kiến hoàn thành 12 năm phổ thông ở nước ngoài.":"在国外已/预计完成12年基础教育。",
  "Có IB, Abitur hoặc GCE A-level.":"持有IB、Abitur或GCE A-level。",
  "Được trường công nhận có học lực tương đương.":"经学校认定具有同等学力。",
  "Với bạn có liên hệ với Trung Quốc":"与中国有渊源的考生",
  "Nếu cha hoặc mẹ có quốc tịch Trung Quốc, cần nộp thêm hồ sơ bổ sung (xem tab \"Nộp hồ sơ\").":"若父母一方拥有中国国籍，需另行提交补充材料（见“提交材料”标签页）。",
  "Tuyển sinh theo 4 hình thức:":"招生方式共4种：",
  "Xét tuyển tổng hợp":"综合型选拔",
  "Tiến cử của trường":"学校推荐",
  "(chỉ định / công mộ),":"（指定校 / 公开募集），",
  "Thi tuyển thông thường":"一般选拔",
  "🌏 Dành cho lưu học sinh nước ngoài":"🌏 面向外国留学生",
  "Cần đọc thêm tài liệu \"Yêu cầu tuyển chọn lưu học sinh\" riêng của trường. Bạn đủ điều kiện nếu thuộc điều kiện chung, hoặc thuộc một trong các trường hợp sau:":"请另行阅读学校的《留学生选拔要项》。符合共同条件，或符合下列情形之一者具备资格：",
  "Đã hoàn thành/dự kiến hoàn thành":"在国外已完成/预计完成",
  "12 năm giáo dục phổ thông":"12年基础教育",
  "ở nước ngoài. Nếu chương trình dưới 12 năm, cần hoàn thành thêm khóa dự bị.":"。若学制不足12年，还需另外完成预备教育课程。",
  "Đã học":"已以“留学”在留资格在经日本法务大臣认定的日语教育机构学习",
  "từ 1 năm trở lên":"1年",
  "tại trường Nhật ngữ được Bộ trưởng Tư pháp công nhận với tư cách lưu trú \"Du học\",":"以上，",
  "hoặc":"或",
  "có năng lực tiếng Nhật tương đương":"具备日语能力，水平相当于",
  "Nếu muốn xin tiến cử từ trường Nhật ngữ, chuyển tiếp hoặc nhảy cấp, hãy liên hệ trực tiếp với trường qua":"如需日语学校推荐、转入或跳级，请直接联系学校，电话",
  "📖 Có xét hồ sơ + bài thi + phỏng vấn":"📖 书面审查 + 考试 + 面试",
  "Chưa học tiếng Trung":"未学过中文",
  "Xét hồ sơ":"书面审查",
  "Viết luận 60 phút (600–800 chữ), chọn 1 trong 5 nhóm chủ đề":"作文60分钟（600–800字），从5组主题中任选1组",
  "Phỏng vấn khoảng 10 phút (tự giới thiệu bằng tiếng Nhật)":"面试约10分钟（用日语自我介绍）",
  "Nhân lực toàn cầu":"全球化人才",
  "Xã hội, giáo dục, việc làm thời AI":"AI时代的社会、教育与就业",
  "Giáo dục ngoại ngữ":"外语教育",
  "Đô thị quốc tế như Thâm Quyến":"深圳等国际化城市",
  "Đô thị đổi mới":"创新城市",
  "Đã học tiếng Trung":"学过中文",
  "Thi viết 60 phút: đọc hiểu và viết luận.":"笔试60分钟：阅读理解与作文。",
  "Miễn thi":"免试",
  "nếu có HSK4 hoặc Trung kiểm (中検) 3 級":"若持有HSK4级或中检（中検）3级",
  "Phỏng vấn khoảng 10 phút (tự giới thiệu bằng tiếng Trung)":"面试约10分钟（用中文自我介绍）",
  "Được":"可",
  "cộng điểm (tối đa 50)":"加分（最多50分）",
  "nếu có chứng chỉ (kiểm định chuyên ngành, Hán tự, Eiken…), báo cáo hoạt động nghiên cứu, hoạt động tình nguyện hoặc ngoại khóa.":"：持有证书（专业检定、汉字检定、英检等）、探究活动报告、志愿服务或课外活动经历。",
  "Tiến cử của trường (chỉ định / công mộ)":"学校推荐（指定校 / 公开募集）",
  "🏫 Xét hồ sơ + phỏng vấn":"🏫 书面审查 + 面试",
  "Chưa học tiếng Trung: xét hồ sơ, phỏng vấn khoảng 10 phút (tiếng Nhật)":"未学过中文：书面审查、面试约10分钟（日语）",
  "Đã học tiếng Trung: xét hồ sơ, phỏng vấn khoảng 10 phút (tiếng Trung). Từ HSK4 trở lên thường được tính là người đã học":"学过中文：书面审查、面试约10分钟（中文）。HSK4级以上者通常按“已学过中文”处理",
  "Có thư tiến cử của hiệu trưởng, trường là nguyện vọng 1 và cam kết nhập học nếu đỗ":"须有校长推荐信，以本校为第一志愿，并承诺录取后入学",
  "Dự kiến tốt nghiệp THPT tháng 3/2027":"预计2027年3月高中毕业",
  "Chỉ định:":"指定校：",
  "điểm trung bình học tập từ":"评定平均",
  "trở lên (sau cộng điểm), học tại trường được trường chỉ định":"以上（加分后），就读于学校指定的高中",
  "Công mộ:":"公开募集：",
  "điểm trung bình từ":"评定平均",
  "trở lên (sau cộng điểm)":"以上（加分后）",
  "Có HSK4+, Trung kiểm 3 級+ hoặc Eiken 2 級+ được":"持有HSK4级以上、中检3级以上或英检2级以上者可",
  "cộng 0.2":"加0.2分",
  "vào điểm trung bình (chỉ cộng 1 mục)":"到评定平均中（仅限加1项）",
  "✏️ Xét hồ sơ + thi 2 môn":"✏️ 书面审查 + 2科考试",
  "Chọn 2 môn trong: Quốc ngữ (hiện đại, cổ văn), Toán (Toán I, A), Tin học I, Ngoại ngữ (Anh hoặc Trung). Mỗi môn 100 điểm, tổng 200 điểm.":"从以下科目中选2科：国语（现代文、古文）、数学（数学Ⅰ、A）、信息Ⅰ、外语（英语或中文）。每科100分，满分200分。",
  "Miễn môn ngoại ngữ":"免考外语科目",
  "nếu có Eiken CSE 2100+, TOEFL iBT 60+, TOEIC 650+, HSK4 hoặc Trung kiểm 3 級":"条件：持有英检CSE 2100分以上、TOEFL iBT 60分以上、TOEIC 650分以上、HSK4级或中检3级",
  "Biết hay chưa biết tiếng Trung không ảnh hưởng đến kết quả đậu rớt":"是否学过中文不影响录取结果",
  "Người đã học tiếng Trung có thể được xét":"学过中文者可视能力和考试成绩考虑",
  "chuyển tiếp hoặc nhảy cấp":"转入或跳级",
  "tùy năng lực và kết quả thi. Hãy ghi rõ nguyện vọng trong form đăng ký online. Sau khi nhập học cần thi công nhận tín chỉ.":"。请在线上报名表中注明意愿。入学后需参加学分认定考试。",
  "Bước 1 · Đăng ký online":"步骤1 · 在线报名",
  "Điền form đăng ký web":"填写网络报名表",
  "Gồm lý do ứng tuyển 200–300 chữ. Báo cáo hoạt động (tình nguyện, ngoại khóa, chứng chỉ) chỉ dành cho xét tuyển tổng hợp":"包括200–300字的报考理由。活动报告（志愿服务、课外活动、证书）仅限综合型选拔提交",
  "Tải lên dữ liệu":"上传资料",
  "Ảnh thẻ 1 tấm (4cm × 3cm, không đội mũ, chụp trong 3 tháng, nền trắng hoặc xanh); ảnh hoặc bản scan màu hộ chiếu; chứng chỉ tiếng Trung (không bắt buộc)":"证件照1张（4cm × 3cm，免冠，3个月内拍摄，白色或蓝色背景）；护照照片或彩色扫描件；中文水平证明（非必须）",
  "Có thể tải lên khi đăng ký, hoặc gửi email trước kỳ thi tới":"可在报名时上传，或在考试前发送电子邮件至",
  "Bước 2 · Gửi hồ sơ qua bưu điện":"步骤2 · 邮寄材料",
  "Học bạ / bản đánh giá (調査書)":"成绩单 / 调查书（調査書）",
  "Không bóc niêm phong. Nếu có bản tiếng Anh thì gửi bản tiếng Anh. Thiếu ngày dự kiến tốt nghiệp thì cần thêm giấy chứng nhận dự kiến tốt nghiệp. Chưa có thì liên hệ trường":"请勿拆封。如有英文版请寄英文版。若未注明预计毕业日期，需另附预计毕业证明。尚未取得者请联系学校",
  "Thư tiến cử":"推荐信",
  "Chỉ dành cho xét tuyển tiến cử: trường chỉ định do trường gửi đến cấp 3; công mộ tải mẫu từ website":"仅限学校推荐选拔：指定校由学校寄往高中；公开募集请从网站下载模板",
  "Gửi đến:":"寄送地址：",
  "Hồ sơ bổ sung nếu cha hoặc mẹ có quốc tịch Trung Quốc":"父母一方拥有中国国籍者的补充材料",
  "Giấy tờ chứng minh sinh ra ngoài Trung Quốc, hoặc giấy tờ chính thức xác nhận đã hủy hộ khẩu / quốc tịch Trung Quốc.":"证明在中国境外出生的文件，或正式证明已注销中国户籍/国籍的文件。",
  "Bản gốc trích lục hộ tịch (戸籍謄本).":"户籍誊本（戸籍謄本）原件。",
  "Bản sao màu hoặc ảnh chụp lịch sử xuất nhập cảnh trong hộ chiếu 4 năm gần nhất.":"近4年护照出入境记录的彩色复印件或照片。",
  "Bản sao màu hoặc ảnh chụp thẻ lưu trú của cha/mẹ có quốc tịch Trung Quốc.":"持中国国籍父/母的在留卡彩色复印件或照片。",
  "Sau khi xét hồ sơ, trường sẽ liên hệ qua điện thoại hoặc email để báo kết quả sơ tuyển, lịch thi và việc nộp lệ phí xét tuyển. Lịch tuyển sinh chi tiết (đợt nhập học tháng 10/2026 và tháng 4/2027) xem tại":"材料审查后，学校将通过电话或电子邮件通知初审结果、考试日程及报名费缴纳事宜。详细招生日程（2026年10月和2027年4月入学批次）请见",
  "tài liệu tiếng Việt của trường":"学校的越南语资料",
  "Chọn từng loại để xem điều kiện và mức học bổng.":"请选择类别查看条件和奖学金金额。",
  "🎁 Nhập học":"🎁 入学",
  "🎯 Ngoại ngữ":"🎯 外语",
  "📚 Thành tích":"📚 成绩",
  "🌐 Thực tiễn xã hội":"🌐 社会实践",
  "🏕️ Du học ngắn hạn":"🏕️ 短期留学",
  "Trong mỗi đợt thi xét, sinh viên xuất sắc nhất đạt yêu cầu của trường sẽ được nhận học bổng này.":"每次评审中，达到学校要求的最优秀学生将获得此奖学金。",
  "Không cần đăng ký riêng, trường tự xét khi nhập học":"无需单独申请，学校在入学时自行审核",
  "Dành cho tân sinh viên có thành tích đầu vào xuất sắc và phẩm hạnh tốt":"面向入学成绩优异且品行良好的新生",
  "Ưu tiên người có chứng chỉ HSK hoặc được trường chỉ định tiến cử":"优先考虑持有HSK证书或获学校指定推荐者",
  "Số lượng rất ít":"名额极少",
  "Cấp cao nhất":"最高档",
  "Cấp trung – cao":"中高档",
  "Cấp trung":"中档",
  "Điểm nổi bật:":"亮点：",
  "sinh viên chứng minh được năng lực tiếng Trung bằng chứng chỉ HSK trước khi nhập học đều được nhận học bổng này.":"入学前以HSK证书证明中文能力的学生，均可获得此奖学金。",
  "Cần nộp đơn đăng ký.":"需提交申请。",
  "Chứng chỉ phải được cấp trong vòng":"证书须在",
  "2 năm trước khi nhập học":"入学前2年内取得",
  "và nộp bản chứng nhận đỗ trước khi nhập học. Nếu có nhiều chứng chỉ, trường lấy mức cao nhất làm chuẩn.":"，并在入学前提交合格证明。如有多个证书，学校以最高等级为准。",
  "Áp dụng từ":"适用于",
  "năm 2":"第2年起",
  "cần nộp đơn":"需提交申请",
  ". Dành cho sinh viên xuất sắc, phẩm hạnh tốt, đạt tiêu chuẩn đánh giá của trường (số lượng có hạn). Mức tham khảo:":"。面向成绩优秀、品行良好、达到学校评价标准的学生（名额有限）。参考标准：",
  "GPA tối thiểu 3.5/4.5":"GPA不低于3.5/4.5",
  "và tỷ lệ chuyên cần (seki)":"且出勤率（seki）",
  "từ 90% trở lên":"90%以上",
  "Hạng nhất":"一等",
  "Hạng nhì":"二等",
  "Hạng ba":"三等",
  "Xét dựa trên:":"评审依据：",
  "Điểm số":"成绩",
  "Chuyên cần":"出勤",
  "Thái độ học tập":"学习态度",
  "Thành tích tổng hợp":"综合表现",
  "Dành cho sinh viên":"面向",
  "từ năm 2 trở lên":"第2年及以上",
  ": tích cực tham gia thực tiễn xã hội, phẩm hạnh tốt, đạt tiêu chuẩn đánh giá của trường.":"的学生：积极参与社会实践、品行良好、达到学校评价标准。",
  "Đóng góp cộng đồng":"社区贡献",
  "Nhiệt huyết":"热情",
  "Học tập":"学习",
  "tuần":"周",
  "Hỗ trợ du học ngắn hạn tại Trung Quốc":"中国短期留学支援",
  "Tổ chức tại Đại học Thâm Quyến cơ sở chính. Học tập, trải nghiệm và tham quan doanh nghiệp vừa và lớn tại Thâm Quyến.":"在深圳大学本部举办。学习、体验，并参观深圳的大中型企业。",
  "✅ Trường hỗ trợ":"✅ 学校提供",
  "Khách sạn 🏨":"酒店 🏨",
  "Hoạt động trải nghiệm":"体验活动",
  "Tham quan doanh nghiệp lớn tại Trung Quốc":"参观中国大型企业",
  "Di chuyển trong Thâm Quyến":"深圳市内交通",
  "Và nhiều hoạt động khác":"以及更多活动",
  "🎒 Sinh viên tự túc":"🎒 学生自理",
  "Vé máy bay":"机票",
  "Chi phí cá nhân":"个人费用",
  "Hình thức":"这是一项",
  "miễn giảm chi phí":"费用减免",
  "du học ngắn hạn (học phí, phí hoạt động).":"制度，适用于短期留学（学费、活动费）。",
  "Cần nộp đơn":"需提交申请",
  ", áp dụng từ năm 2 cho sinh viên tham gia chương trình ngắn hạn tại Đại học Thâm Quyến cơ sở chính,":"，面向从第2年起参加深圳大学本部短期项目的学生，",
  "không áp dụng với sinh viên nhảy cấp":"不适用于跳级学生",
  ". Số lượng có hạn, ưu tiên sinh viên có thành tích tốt.":"。名额有限，成绩优异者优先。",
  ".":"。",
  ",":"，",
  "__ready":true
};
